### ISSUE TITLE
[Feature Reuqest] Using it like an API on our Github readme

### ISSUE THREAD

**Issue by Nirzak** [faheel/GitHub-contributions#5]
Hi, how about slightly modify the project to host it, online hosts, like Netlify, Vercel and then use it as an API to list the repositories we have contributed to on our readme profiles?

**Comment by faheel** [comment]
Adding the functionality to use it like an API and to host the API somewhere is out of scope for now.

I can modify the project and publish it as a package on PyPI to allow other developers to easily resuse it in their projects, and then they can host their projects somewhere and use it however they want. An issue for this was created a long time ago by me at #2, but I haven't had the time to refactor and package it.

**Comment by Nirzak** [comment]
> Adding the functionality to use it like an API and to host the API somewhere is out of scope for now.
> 
> I can modify the project and publish it as a package on PyPI to allow other developers to easily resuse it in their projects, and then they can host their projects somewhere and use it however they want. An issue for this was created a long time ago by me at #2, but I haven't had the time to refactor and package it.

Ok, that will be also helpful if you do so.
